language: java
jdk:
- oraclejdk8
script:
  - cd src 
  - if [[ -z "$TRAVIS_TAG" ]]; then PHASE=package; else PHASE=deploy; fi
  - mvn $PHASE --settings .travis.settings.xml
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: qJrC3DeZ5XCyM1JaQrgiGRYK7fviMyNKzhb8L+9Yqyc0jSlfLlHRoKJKCm/YOvPgllUTkW7EDBWiO2tY93DKV7jf9fig5Pypv1Qv4d+B0HNf7jlY8Wmb53s4Zxkeu3ghlCZOeRlzobXmrofCwiGJtJTemMB8509AzzS0VmqqSzJR2RKonZyyLbiBlxszvJEt8ycuBF831cZzKZ1xHozNgNQqz14xZYWlZCj2pouPUbKDDqwAoGrRLHV6ciN3hVDXPGP0Ct8U11FFAk/8D21O4M0Py2fs4blXykVtARGYPB4zdFY7gKP9ce9DcOJ08Mi6wibg7JiMGxl4csGfVc8D7OpF/7fgMvS/e5Hrusrq0SuRaILMDvnL+S9ogn5/4i4yrhvk66cJOKmwzqDVUlcI5lNR5O3xdKmdCQPpslaRMTWoThJKJiaTYoqm+46Gb6te48iQJ4q53YiZgho+f5yNoogIp3Z5gqhQ02rx6BZ+DGzO4Cvcgv7d2H6Cc7LDdOxIfMyr+noYCLX601AjsY+utNedKtFV/+YH4BMNUpJFe8/RwpKcQELhr4IS1YfHr3WCwRaK2wDVanjF8LVOBbVPbR+xBgZ02oxNbyInDFbPlxDx5bATi2Url7j9IBnzVXjzCPx9rotbUVUxtFf4tMdh4Sva+pJvbtTjjIQXESYHNTk=
  file_glob: true
  file: "*/target/*.zip"
  skip_cleanup: true
  on:
    repo: INTER-IoT/gateway-extensions-virtual
    tags: true
    branches:
      only:
        - master
env:
  global:
    - secure: wcUfQDRm8bCEn/ktw5/V9tROXmRd8kf4Vp/AgUf3+0cy5ftV4LoH0GUZYi6PvjGxdrIa6oo02v+umYaTKv1ClAiXnzwAgqrAM/4YJ7x/PkOCq9EYuK0fnSmwduO7uYCsBR5olvrItz37vY2qmLoZk0OwoVg6MJCFXhgXKy0KZBax2IRGcrdkq6k8auH8NQzmcUZzxD6ZlrVB8wHXi9Ec+OZqae7VgmCujeQHEzgZ0My03uHG02vPhsxoo7bCmmAnEh9zOjJsiKQQqWCKKoAuSEeWPRwWfxTqclmmgSBOizWHlKuR3G5qxSs5XP7IhLWTW0+bfeauRACBLwtDl28EI11eMPbtuWefy5KGJkDnF6mAEDgTtGL3XThIWaiExoklOuBCIZsdpa/RCzuan8CwHoegh7bstAmNFoA4NrnxgPmdXo1HFLjhayF1OwGwqu98sxf0LolGSYGz5mcixwjyuN9YWjWuCM1ZJaB8/3Z+aKCmCVzbIlsHyhcVdA9xgn+9ZSC3pk3ZeH+IySaYTvjlY0xMRsTBxTKydzfD8M0XHSH9scoa+7I07qAvO3c6WPpXxz5dBm2fLQZ6k6H5hDLUWtsF6jMF0V5Y4HP+CAZ5UOL/qOpfGIYufhIqE9/qqJK8iJnpc7qDL1S48NhSFSd2ay+qWl5GSlwj5B0Mmir1ctc=
    - secure: yPWUaqmbJxQewjpxVRnZWvsGOGa+5xXNoHv2YFhC/aQ1KovXuFw/DGyZkACoHyGP7kmBluh25wGYJBBiVK3QkWp7HFZvEARglQo9XcgVK2WAs+Bpu4J0V6QSwWUr5IdXXyrj6Sk9PC+B8OOWPu7Hy/nTG/ncj08pOYlT/97ZKoINwxleEgpQZdF5UrkqGUqj3ZItTbrzSxg0oUyd1ppCeOFMyJZgOCxrIckUXdwJSw658dkkGKTnfaBLKfrLGHKIYfQcFRnzDdS0z3EywLIlMJbxXLuOccYXo4bI/VX9o+WVedKuGcUuA4cRxGfE97VMMSTbPZzv3s+a3HcnDI/oUORd17aCUzl6QRXksokQOLmzP+hCfwRQFNzITVf0gV3wKSLWoV9C93TBFSCD2fbdIcDh6gB3ec4kurPkhubuqx4RniB8LlPMmxmNyDgSl7Ua/QSkE7/TQfn2pZy2rJsFBtE5arS+UnxF5ji70ltreAfEXP5+OHTHMbU3eBmuFT3MQzDitT2OqkwJalmt2uTN/G03UTknxjUPVNjsrCDrDqSqDF59j91Vh8dMVzfqoIXIz1w46gQHZdzFLA2r/vBCtjvT6/K2zWc8q7ZieivaVp6jN01ZE+Bw+qxS/QSWlhlU4m20/l+yUW5ooHnrNUTglR6WhhfybIZMxxOn2XG4TuY=
